---
title: "How to Use the Excess Mortality Calculator"
output:
  bookdown::html_book:
    number_sections: false
---


### Data Preparation and Format

The input data file should be a CSV file containing death counts over time, and possibly by sub-population. The required data input is in the "long format", where each row correspond to the death count of a given (sub-)population at a given time period. The dataset should include at least the following required columns (with the exact column names):

+ `year`: numerical value, e.g., 2015, 2016, ...
+ `month` or `week`: numerical value. For monthly data input, the `month` field is required to be from 1 to 12. For weekly data input, the `week` field is required to be from 1 to 53.
+ `deaths`: numerical value. This is the death count for the corresponding year and month/week. 


There are additional columns that can be included in the data. The column names of these fields can be user-defined.

+ **Sex**: if death count of a given row is for a specific sex.
+ **Age**: if death count of a given row is for a specific age group. Please note the age needs to be grouped into bins.
+ **Population**: the total population corresponding to the row. For example, for a row corresponding to male and age group of 65 or above in a certain month. The `death` field specifies the number of male deaths above age 65 in that month, and the `population` field specifies the total population of male above age 65 in that month.

The App adds up all deaths within each month/week to produce the total deaths and total population at each time point. When both sex and age are specified, the App adds up all deaths within each age/sex to produce the marginal total deaths and total population by age and sex. 

The variables corresponding to age, sex, and population need to be specified manually in the App. If the variables are named "sex", "age", and "population" already, the variables will be automatically picked up by the App. When left unspecified, the App will ignore the age/sex breakdown.

We recommend having 3 to 10 years of historical data as input to the App.

### Step-by-Step Guide to Model Fitting 

1. Upload the data file prepared according to the previous section.
2. Choose relevant time period used in the data: monthly or weekly. If the choice is not made or is not consistent with the data file, an error will be displayed in the panel on the right.
3. Choose which model to fit: Poisson regression or the simple baseline model. Poisson regression model can take a minute to fit and a waiting symbol will display on the screen until model fitting is fully done. 
4. If population size information exists, select the column corresponding to the population size. If there is a column named "population" in the data, it will be automatically selected. If the variables are named differently, manual selection is required.
5. If excess by sex and age is of interest, select sex and age variables in the data. If there are columns named "sex" or "age" in the data, they will be automatically selected. If the variables are named differently, manual selection is required.
6. Click "Analyze my data" to fit the model.

### Interpreting Results

#### Excess Mortality Tab
This tab provides results **for a specific age/sex combination**, specified by the user in the selector above. The default view is the overall death counts, i.e., both Sex and Age set to "All". The Plot Type option allows user to switch between two visualizations:

1. Death Counts: Line plot of expected and observed death counts. 95% uncertainty intervals are also shown for the expected death counts. Expected death counts after 2020 are predictions based on historical data, so they have larger uncertainties. The difference between the two lines are the excess death counts.
2. Excess Death Counts: Line plot of the excess death counts and the associated 95% uncertainty interval. 

The table below contains the actual deaths, excess deaths, and uncertainty intervals for the excess deaths, for the selected age and sex combination after 2020.

Both the plot and table can be downloaded using the corresponding download buttons. The table can be downloaded in multiple formats. 


#### Comparison By Age And Sex Tab
This tab provides results comparing multiple sub-populations. Comparison plots by sex, by age, or by both sex and age are specified by the user in the selector, depending on which sub-populations are specified in the input data. There are three plots:

1. Death Counts: Same death count plot as in the first tab, but for each sub-population separately.
2. Excess Death Counts: Same excess death count plot as in the first tab, but for each sub-population separately.
3. Excess Death Counts (Overlay): Excess death counts and their uncertainty for all sub-populations in one figure. This plot can be difficult to read when there are too many sub-populations. For visualizing only a subset of sub-populations, Lines and the uncertainty bands can be removed manually by clicking on the legend to the right.

The full plot can be downloaded using the corresponding download button on the top. 

When hovering over the graph, a toolbar will show on the top right corner of the plot, which allows additional operations on the plot including zooming and selection. The modified graph can be downloaded using the "Download plot as a png" option in the toolbar.

#### Historical Data Explorer Tab

The raw death counts by month or week are visualized and tabulated in this tab, **for a specific age/sex combination**, specified by the user in the selector above.
